artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  datasets:
    source_URL: "geolifeclef-2024"
    type: "competition"
    local_data_file: artifacts/data_ingestion/geolifeclef-2024.zip
    unzip_dir: artifacts/data_ingestion/geolifeclef-2024


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FOLDERS: ["artifacts/data_ingestion/geolifeclef-2024/EnvironmentalRasters",
                          "artifacts/data_ingestion/geolifeclef-2024/PA_Test_SatellitePatches_NIR",
                          "artifacts/data_ingestion/geolifeclef-2024/PA_Test_SatellitePatches_RGB",
                          "artifacts/data_ingestion/geolifeclef-2024/PA_Train_SatellitePatches_NIR",
                          "artifacts/data_ingestion/geolifeclef-2024/PA_Train_SatellitePatches_RGB",
                          "artifacts/data_ingestion/geolifeclef-2024/PA-test-landsat_time_series",
                          "artifacts/data_ingestion/geolifeclef-2024/PA-train-landsat_time_series",
                          "artifacts/data_ingestion/geolifeclef-2024/TimeSeries-Cubes"
                    ]
  ALL_REQUIRED_FILES: [
    "artifacts/data_ingestion/geolifeclef-2024/GLC24_P0_metadata_train.csv",
    "artifacts/data_ingestion/geolifeclef-2024/GLC24_PA_metadata_test.csv",
    "artifacts/data_ingestion/geolifeclef-2024/GLC24_PA_metadata_train.csv",
    "artifacts/data_ingestion/geolifeclef-2024/GLC24_SAMPLE.csv"
  ]


data_loading_and_transformation:
  root_dir: artifacts/data_loader
  dataset: artifacts/data_ingestion/geolifeclef-2024
  save_data: artifacts/data_loader/geolifeclef-2024

initialize_multimodal:
  root_dir: artifacts/multi_modal
  data_loader_path: artifacts/data_loader

model_trainer:
  root_dir: artifacts/model_trainer
  multimodal: artifacts/multi_modal/multimodal_ensemble_model.pth
