artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  datasets:
    source_URL: "geolifeclef-2024"
    type: "competition"
    local_data_file: artifacts/data_ingestion/geolifeclef-2024.zip
    unzip_dir: artifacts/data_ingestion/geolifeclef-2024
